version: '2'

services:


### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=false
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        #extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
        #    - "dockerhost:10.0.75.1"
        tty: true

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "6379:6379"

### Laravel Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../:/var/www/laravel
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/sessions:/sessions

### Add more Containers below ###############################

### HAProxy Container #######################################

    lb:
#        image: dockercloud/haproxy
        build:
            context: ./lb
            dockerfile: Dockerfile
        links:
            - web
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./logs/supervisor/:/var/log/supervisor
        tty: true

### WEB Container ###########################################

    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./logs/supervisor/:/var/log/supervisor
        expose:
            - "80"
        links:
            - workspace
