FROM php:7.0-fpm

MAINTAINER appkr <juwonkim@me.com>

ENV DEBIAN_FRONTEND noninteractive

##
# Configure Supervisor
##

# ADD supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN apt-get update \
    && apt-get install -my supervisor \
    --no-install-recommends \
    --no-install-suggests;

##
# Configure Nginx
##

RUN  apt-get install -y --force-yes nginx \
    --no-install-recommends \
    --no-install-suggests;

ADD nginx.conf /etc/nginx/

RUN echo "upstream php-upstream { server php-fpm:9000; }" > /etc/nginx/conf.d/upstream.conf

##
# Configure FPM
##

ADD php.ini /usr/local/etc/php/conf.d
ADD www.conf /usr/local/etc/php-fpm.d/

RUN apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    --no-install-recommends \
    --no-install-suggests \
    && rm -r /var/lib/apt/lists/*

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql;

# Install Memcached for php 7
RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p /usr/src/php/ext/memcached \
    && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && docker-php-ext-configure memcached \
    && docker-php-ext-install memcached \
    && rm /tmp/memcached.tar.gz;

# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug;

##
# Boot
##

RUN rm /etc/nginx/sites-available/default
ADD laravel.conf /etc/nginx/sites-available/
#COPY ./cmd.sh /

RUN usermod -u 1000 www-data

WORKDIR /var/www/laravel

EXPOSE 80 443

CMD ["/usr/bin/supervisord"]